theme: jekyll-theme-minimal
title: Junior American Politics Virtual Workshop
description: Landing page for the Junior American Politics Virtual Workshop, a venue for junior americanist scholars to share their research.
logo: /Capital.jpg
